# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x03\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"\x8f\x01\n\rAppendRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\x03\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12\x17\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x06.Entry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\"4\n\x0eGetLeaderReply\x12\x11\n\tleader_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\" \n\x0eSuspendRequest\x12\x0e\n\x06period\x18\x01 \x01(\x03\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1b\n\x08SetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"*\n\x08GetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"1\n\x05\x45ntry\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\".\n\x0eResultWithTerm\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x0e\n\x0c\x45mptyMessage2\x92\x02\n\x08RaftNode\x12.\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\x0f.ResultWithTerm\"\x00\x12\x32\n\rAppendEntries\x12\x0e.AppendRequest\x1a\x0f.ResultWithTerm\"\x00\x12-\n\tGetLeader\x12\r.EmptyMessage\x1a\x0f.GetLeaderReply\"\x00\x12+\n\x07Suspend\x12\x0f.SuspendRequest\x1a\r.EmptyMessage\"\x00\x12\"\n\x06SetVal\x12\x0b.SetRequest\x1a\t.SetReply\"\x00\x12\"\n\x06GetVal\x12\x0b.GetRequest\x1a\t.GetReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=14
  _globals['_VOTEREQUEST']._serialized_end=110
  _globals['_APPENDREQUEST']._serialized_start=113
  _globals['_APPENDREQUEST']._serialized_end=256
  _globals['_GETLEADERREPLY']._serialized_start=258
  _globals['_GETLEADERREPLY']._serialized_end=310
  _globals['_SUSPENDREQUEST']._serialized_start=312
  _globals['_SUSPENDREQUEST']._serialized_end=344
  _globals['_SETREQUEST']._serialized_start=346
  _globals['_SETREQUEST']._serialized_end=386
  _globals['_SETREPLY']._serialized_start=388
  _globals['_SETREPLY']._serialized_end=415
  _globals['_GETREQUEST']._serialized_start=417
  _globals['_GETREQUEST']._serialized_end=442
  _globals['_GETREPLY']._serialized_start=444
  _globals['_GETREPLY']._serialized_end=486
  _globals['_ENTRY']._serialized_start=488
  _globals['_ENTRY']._serialized_end=537
  _globals['_RESULTWITHTERM']._serialized_start=539
  _globals['_RESULTWITHTERM']._serialized_end=585
  _globals['_EMPTYMESSAGE']._serialized_start=587
  _globals['_EMPTYMESSAGE']._serialized_end=601
  _globals['_RAFTNODE']._serialized_start=604
  _globals['_RAFTNODE']._serialized_end=878
# @@protoc_insertion_point(module_scope)
